### ISSUE TITLE
date/location for next meetup

### ISSUE THREAD

**Issue by stoeffel** [elm-zurich/meetup#3]
- [ ] location
- [x] date 📆 23.09

**Comment by stoeffel** [comment]
@nerdinand I think you said we can do it again at simplificator, right?

**Comment by stoeffel** [comment]
how about doing the next meetup on the 27. of September?

**Comment by grossbart** [comment]
Dates that would work for me are the 14./21./22. and 29.9. But I'm only one of many, so pick whatever fits most people best :smile:

**Comment by stoeffel** [comment]
I created a doodle, to make it easier to find a date.
@fabiofilli could you post it on the meetup group?
http://doodle.com/poll/uzd29saztqv45vib

**Comment by stoeffel** [comment]
http://doodle.com/poll/uzd29saztqv45vib
pinging @nerdinand @jwoudenberg @pukkamustard.
Please fill out the doodle.

@pukkamustard <- Is that you Adu from Dividat?

**Comment by pukkamustard** [comment]
@stoeffel Yes, this is Adu from Dividat.

Unfortunately, I'll be traveling until middle of October and won't be able to make it to the next meetup. I hope to be back for the one after that!

**Comment by stoeffel** [comment]
> @stoeffel Yes, this is Adu from Dividat.

😄 

> Unfortunately, I'll be traveling until middle of October and won't be able to make it to the next meetup. I hope to be back for the one after that!

Too bad. Have a nice trip.

**Comment by jwoudenberg** [comment]
Seems Friday the 23rd is a good option. Should we pick that?

**Comment by stoeffel** [comment]
I have to check with my babysitter. Will let you know by Wednesday. 😄

**Comment by stoeffel** [comment]
Date is set! 23.09

**Comment by fillidefilla** [comment]
Alright :) so let's spread the date!!
