### ISSUE TITLE
how can we get more participants?

### ISSUE THREAD

**Issue by stoeffel** [elm-zurich/meetup#4]
ideas welcome

**Comment by stoeffel** [comment]
one idea: pinging people on github :laughing: 

f.e. @queckezz, @naehrstoff would be cool to see you at the next meetup!

**Comment by grossbart** [comment]
I'd love to come and there are also some co-workers who want to attend. But – there's always a but blablabla – Tuesdays won't be possible for me for the next half year or so as suggested in #3.

So one idea to allow more interested people to come could be to hold every meetup on a different day of the week.
