### ISSUE TITLE
Meetup December

### ISSUE THREAD

**Issue by stoeffel** [elm-zurich/meetup#8]
- [x] location
- [x] date
- [ ] talks ( **please comment in here, if you want to give a lightning talk!** )

**Comment by stoeffel** [comment]
I will create a doodle to find a date, tomorrow.

**Comment by fillidefilla** [comment]
@nerdinand is 15th of December at Simplificator fix?

**Comment by stoeffel** [comment]
btw. I've got a talk.

**Comment by nerdinand** [comment]
@fabiofilli @stoeffel yes, the 15th at Simplificator is fine

**Comment by stoeffel** [comment]
let's spread the word and call for lightning talks. 10min max okay?
